### ISSUE TITLE
Provide a readiness/liveliness endpoint

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-vnv#41]
Check [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) and [this](https://github.com/sonata-nfv/tng-devops/wiki/Liveness-and-Readiness-probes).

**Comment by jbonnet** [comment]
This case is similar to the one shown [here](https://github.com/sonata-nfv/tng-devops/wiki/Liveness-and-Readiness-probes#http), but with a `/pings` (plural) endpoint.

So the configuration should be something like the following:

```yaml
    livenessProbe:
      httpGet:
        path: /pings
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
```
